In [12]:
import random
import numpy as np

machines = ['A', 'B', 'C']

M = 3
N_plays = 10
eps = 0.2

play = 1

# N = number of times machine selected
# R = rewards
# Q = estimated reward
N = np.zeros((M, N_plays + 1))
R = np.zeros((M, N_plays + 1))
Q = np.zeros((M, N_plays + 1))

# Maximum number of times each machine can be selected
max_times = 4

while play <= N_plays:

    r = random.uniform(0, 1)

    # Current number of times each machine has been selected
    count = N[:, play - 1]

    # Machines which are still allowed to be selected
    available = [i for i in range(M) if count[i] < max_times]

    # Find highest Q among available machines
    id_max = available[np.argmax(Q[available, play - 1])]

    if r < eps:

        print("Exploration")

        # Exploration: select randomly except highest-Q machine
        explore_ids = [i for i in available if i != id_max]

        # If only one machine is available, select it
        if len(explore_ids) > 0:
            id = random.choice(explore_ids)
        else:
            id = id_max

    else:

        print("Exploitation")

        # Select highest-Q machine
        id = id_max

    print(f"Now select machine {machines[id]}")
    reward = int(input("Enter reward: "))

    # Copy previous values
    N[:, play] = N[:, play - 1]
    R[:, play] = R[:, play - 1]
    Q[:, play] = Q[:, play - 1]

    # Update selected machine
    old_count = N[id, play - 1]

    N[id, play] = old_count + 1
    R[id, play] = R[id, play - 1] + reward

    # Incremental sample-average formula
    Q[id, play] = Q[id, play - 1] + (
        reward - Q[id, play - 1]
    ) / N[id, play]

    play = play + 1


# ------------------------------------------------
# Display Results
# ------------------------------------------------

print("\nN Table:")
print(N[:, 1:])

print("\nR Table:")
print(R[:, 1:])

print("\nQ Table:")
print(Q[:, 1:])

print("\nFinal Results")
print("--------------------------------")

for i in range(M):
    print(
        f"Machine {machines[i]}: "
        f"Count = {int(N[i, N_plays])}, "
        f"Total Reward = {int(R[i, N_plays])}, "
        f"Q = {Q[i, N_plays]:.2f}"
    )

print("\nTotal reward received =", int(np.sum(R[:, N_plays])))

Exploitation
Now select machine A
Enter reward: 4
Exploitation
Now select machine A
Enter reward: 3
Exploitation
Now select machine A
Enter reward: 2
Exploitation
Now select machine A
Enter reward: 5
Exploitation
Now select machine B
Enter reward: 6
Exploitation
Now select machine B
Enter reward: 7
Exploitation
Now select machine B
Enter reward: 5
Exploration
Now select machine C
Enter reward: 4
Exploitation
Now select machine B
Enter reward: 8
Exploitation
Now select machine C
Enter reward: 3

N Table:
[[1. 2. 3. 4. 4. 4. 4. 4. 4. 4.]
 [0. 0. 0. 0. 1. 2. 3. 3. 4. 4.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 2.]]

R Table:
[[ 4.  7.  9. 14. 14. 14. 14. 14. 14. 14.]
 [ 0.  0.  0.  0.  6. 13. 18. 18. 26. 26.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  4.  7.]]

Q Table:
[[4.  3.5 3.  3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [0.  0.  0.  0.  6.  6.5 6.  6.  6.5 6.5]
 [0.  0.  0.  0.  0.  0.  0.  4.  4.  3.5]]

Final Results
--------------------------------
Machine A: Count = 4, Total Reward = 14, Q = 3.50
Machine B: Co