In [30]:


  import numpy as np
import random

# Machine initialization
machines = ['A', 'B', 'C']

M = 3
N_play = 3
eps = 0.2

# Initialize N, R and Q
N = np.zeros((M, N_play + 1), dtype=int)
R = np.zeros((M, N_play + 1), dtype=int)
Q = np.zeros((M, N_play + 1), dtype=float)

play = 1

while play <= N_play:

    # Copy previous values
    N[:, play] = N[:, play - 1]
    R[:, play] = R[:, play - 1]
    Q[:, play] = Q[:, play - 1]

    # Generate random number
    r = random.uniform(0, 1)

    print("\n" + "=" * 40)
    print("Play", play)
    print("Random number =", round(r, 4))

    # Epsilon-Greedy
    if r < eps:
        print("Explore")

        # Randomly select machine
        id = random.randint(0, M - 1)

    else:
        print("Exploit")

        # Select machine with highest Q
        id = np.argmax(Q[:, play - 1])

    print(f"Play with machine {machines[id]}")

    # Enter reward
    reward = int(input("Enter reward: "))

    # Update participation
    N[id, play] = N[id, play - 1] + 1

    # Store reward
    R[id, play] = reward

    # Incremental Q update
    Q[id, play] = (
        Q[id, play - 1]
        + (R[id, play] - Q[id, play - 1]) / N[id, play]
    )

    play = play + 1


print("=" * 50)
print("Participation of each machine in each play")
print("=" * 50)
print(N)

print("=" * 50)
print("Rewards of each machine in each play")
print("=" * 50)
print(R)

print("=" * 50)
print("Estimated future Rewards of each machine")
print("=" * 50)
print(Q)


Play 1
Random number = 0.2668
Exploit
Play with machine A
Enter reward: 3

Play 2
Random number = 0.161
Explore
Play with machine B
Enter reward: 6

Play 3
Random number = 0.3743
Exploit
Play with machine B
Enter reward: 7
Participation of each machine in each play
[[0 1 1 1]
 [0 0 1 2]
 [0 0 0 0]]
Rewards of each machine in each play
[[0 3 3 3]
 [0 0 6 7]
 [0 0 0 0]]
Estimated future Rewards of each machine
[[0.  3.  3.  3. ]
 [0.  0.  6.  6.5]
 [0.  0.  0.  0. ]]
